name: Build Blender Addon

on:
    push:
        branches:
            - main
        tags-ignore:
            - "v*.*.*" # We auto-tag, so ignore manual ones

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Extract version from __init__.py
              id: get_version
              run: |
                  VERSION=$(grep -Po '(?<=version=)[^)]*' src/__init__.py | tr -d ' ,()')
                  echo "VERSION=${VERSION}" >> $GITHUB_ENV
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Prepare addon
              run: |
                  mkdir build
                  cp -r src build/ActionTables
                  cd build
                  zip -r ../ActionTables.zip ActionTables

            - name: Upload artifact (always)
              uses: actions/upload-artifact@v4
              with:
                  name: ActionTables
                  path: ActionTables.zip

            - name: Create Git tag
              if: github.ref == 'refs/heads/main'
              run: |
                  git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
                  git push origin v${{ env.VERSION }}

    release:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        permissions:
            contents: write

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: ActionTables
                  path: .

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: "ActionTables ${{ github.ref_name }}"
                  files: ActionTables.zip
